apply plugin: 'com.android.application'

android {
    namespace 'com.ctrnative'
    compileSdk 34

    defaultConfig {
        applicationId "com.ctrnative"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static", "-DCTR_NATIVE=ON"
                abiFilters 'armeabi-v7a', 'x86'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt"
            version "3.22.1"
        }
    }

    sourceSets {
        main {
            java.srcDirs = [
                'src/main/java',
                '../../externals/SDL/android-project/app/src/main/java'
            ]
            res.srcDirs = [
                'src/main/res'
            ]
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
